### ISSUE TITLE
optfir has GPLv3 License

### ISSUE THREAD

**Issue by garbagetrash** [mwickert/scikit-dsp-comm#18]
I noticed your sk_dsp_comm/optfir.py is GPLv3... I'm no lawyer, but I _think_ this requires you to license this module as GPLv3 as well [[ref1](https://softwareengineering.stackexchange.com/questions/87446/using-a-gplv3-python-module-will-my-entire-project-have-to-be-gplv3-licensed), [ref2](https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3))].

It looks like it'd be pretty easy to remove this dependency by simply reimplementing fir_design_helper.py to not require optfir.remezord.  I know [scipy.signal](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.remez.html) provides a remez algorithm... perhaps if you just figure out a way to use that instead you can avoid the GPLv3 copyleft?

You could also simply make the whole scikit-dsp-comms module GPLv3, if you would prefer.  I'm personally not invested, I just want to let you know I think there's an inconsistency here that you should probably address.

**Comment by mwickert** [comment]
Garbagetrash,

Thanks for your comment. I am aware of this issue and have a plan to fix it.

As far as I know scipy.signal does not have this function, but in 2013 was talking about adding it.

Mark Wickert

**Comment by mwickert** [comment]
The fixes have been made in my local repo and are ready to be pushed and reviewed from the develop branch.
